

def search_form(year, semester, area='', subarea=''):
    return {
        'srchOpenSchyy': str(year),
        'srchOpenShtm': semester,
        'srchOpenUpSbjtFldCd': area,
        'srchOpenSbjtFldCd': subarea,
        'srchCond': '1',
        'srchCptnCorsFg': '',
        'srchOpenShyr': '',
        'srchSbjtCd': '',
        'srchSbjtNm': '',
        'srchOpenUpDeptCd': '',
        'srchOpenDeptCd': '',
        'srchOpenMjCd': '',
        'srchOpenSubmattCorsFg': '',
        'srchOpenSubmattFgCd': '',
        'srchOpenPntMin': '',
        'srchOpenPntMax': '',
        'srchCamp': '',
        'srchBdNo': '',
        'srchProfNm': '',
        'srchTlsnAplyCapaCntMin': '',
        'srchTlsnAplyCapaCntMax': '',
        'srchTlsnRcntMin': '',
        'srchTlsnRcntMax': '',
        'srchOpenSbjtTmNm': '',
        'srchOpenSbjtTm': '',
        'srchOpenSbjtTmVal': '',
        'srchLsnProgType': '',
        'srchMrksGvMthd': '',
        'srchFlag': '',
    }
