# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('year', 'semester', 'code', 'number')]),
        ),
    ]
