# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170116_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_code', models.CharField(max_length=30)),
                ('to_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='replace',
            unique_together=set([('from_code', 'to_code')]),
        ),
    ]
